# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps_oan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='pub',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='url',
        ),
        migrations.AddField(
            model_name='beer',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beer',
            name='pubs',
            field=models.ManyToManyField(to='taps_oan.Pub'),
        ),
        migrations.AddField(
            model_name='beer',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
