# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taps_oan', '0002_auto_20170223_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='name',
            new_name='title',
        ),
    ]
