# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps_oan', '0003_auto_20170223_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='pubs',
        ),
        migrations.AlterField(
            model_name='beer',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
