# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps_oan', '0004_auto_20170223_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='beers',
            field=models.ManyToManyField(to='taps_oan.Beer'),
        ),
    ]
