# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps_oan', '0005_pub_beers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
