# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps_oan', '0006_auto_20170223_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='beers',
            field=models.ManyToManyField(blank=True, to='taps_oan.Beer'),
        ),
    ]
